# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DDM trials generation with fixed post-decision accumulation time
#' 
#' @description This function generates trials using the Drift Diffusion Model. Additional
#' evidence is accumulated for a fixed time after the decision boundary has been reached.
#' Note: here, decision boundaries are a and -a and starting point is equal to a*z.
#' 
#' @param v Drift rate
#' @param a Decision boundary, evidence at t = 0 is equal to a*z. Decision boundaries are a and -a
#' @param ter Non-decision time
#' @param z Starting point bias in evidence. For unbiased DDM, use z = 0
#' @param ntrials Number of DDM trials to generate
#' @param s Scaling parameter
#' @param dt Time step size
#' @param t2time Post-decision accumulation time
#' @param postdriftmod V-ratio. If equal to 1, post-decision drift rate is equal to decision drift rate
#' @export
DDM_with_confidence_slow <- function(v, a, ter, z, ntrials, s, dt, t2time, postdriftmod) {
    .Call('_myPackage_DDM_with_confidence_slow', PACKAGE = 'myPackage', v, a, ter, z, ntrials, s, dt, t2time, postdriftmod)
}

#' DDM trials generation with multiple post-decision accumulation time
#' 
#' @description This function generates trials using the Drift Diffusion Model. Additional
#' evidence is accumulated for a fixed time after the decision boundary has been reached.
#' Note: here, decision boundaries are a and -a and starting point is equal to a*z.
#' 
#' @param v Drift rate
#' @param a Decision boundary, evidence at t = 0 is equal to a*z. Decision boundaries are a and -a
#' @param ter Non-decision time
#' @param z Starting point bias in evidence. For unbiased DDM, use z = 0
#' @param ntrials Number of DDM trials to generate. Must be a multiple of length(t2time) 
#' so that all confidence RT trials are repeated the same number of times
#' @param s Scaling parameter
#' @param dt Time step size
#' @param t2time Vector containing the whole confidence RT distribution
#' @param postdriftmod V-ratio. If equal to 1, post-decision drift rate is equal to decision drift rate
#' @export
DDM_with_confidence_slow_fullconfRT <- function(v, a, ter, z, ntrials, s, dt, t2distribution, postdriftmod) {
    .Call('_myPackage_DDM_with_confidence_slow_fullconfRT', PACKAGE = 'myPackage', v, a, ter, z, ntrials, s, dt, t2distribution, postdriftmod)
}

